version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
