# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rit-events-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install server dependencies
        run: |
          cd server
          npm install
      
      - name: Install and build client
        run: |
          cd client
          npm install
          npm run build
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BB84982AED3439F9C92D3D5B13A3270 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B9B12914A0943349A363A0670D810FF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_615AA9BB9C0742719EB383D8B313E360 }}
      
      - name: Set Azure App Service startup command
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'rit-events-app'
          slot-name: 'Production'
          app-settings-json: '{"STARTUP_COMMAND": "node server/index.js"}'

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'rit-events-app'
          slot-name: 'Production'
          package: .
          
